version: '3'

services:
  app:
    build: .
    command: /bin/sh -c ("python scheduler/manage.py makemigrations && python scheduler/manage.py migrate && python scheduler/manage.py runserver 0.0.0.0:8000")
    environment:
      - Debug=1
    env_file:
      - .env
    image: scheduler
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    restart: on-failure
    volumes:
      - ./:/scheduler

      
  postgres:
    build: ./database/
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /var/lib/postgresql/data
    

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 8080:8080

