version: '3.8'

services:
  
      
setup:
  addons:
    - plan: heroku-postgresql
        as: DATABASE
      
    build: ./database/
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build: .
    command: /bin/sh -c ("python scheduler/manage.py makemigrations && python scheduler/manage.py migrate && python scheduler/manage.py runserver 0.0.0.0:8000")
    environment:
      - Debug=1
      - REDIS_URL=redis://cache
    env_file:
      - .env
    image: scheduler
    ports:
      - "8000:8000"
    depends_on: 
      - heroku-postgresql
    restart: on-failure




 