# Generated by Django 3.2.8 on 2021-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('post_id', models.CharField(default=None, max_length=11)),
                ('scheduled_id', models.CharField(default=None, max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
