# Generated by Django 3.0.5 on 2021-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongLivedAccessToken',
            fields=[
                ('access_token', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('token_type', models.CharField(max_length=500)),
                ('expires_in', models.DateField(default=False)),
                ('date_created', models.DateField(default=False)),
            ],
        ),
    ]
