# Generated by Django 3.1.7 on 2021-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('photo_id', models.CharField(default=None, max_length=11, primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=255, null=True)),
                ('post_caption', models.CharField(max_length=5000, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_twitter', models.BooleanField(default=False)),
                ('is_facebook', models.BooleanField(default=False)),
                ('is_linkedin', models.BooleanField(default=False)),
                ('datetime_to_publish', models.DateField()),
            ],
        ),
    ]
